// ── PRODUCT DATA ──
const PRODUCTS = [
  { id:1, name:'VedaProtein Elite Whey', category:'Protein Powders', catKey:'protein', emoji:'💪', badge:'Best Seller', price:1299, mrp:1599, rating:5, reviews:128, desc:'24g protein per scoop. Mixes instantly. Chocolate & Vanilla flavors. Ideal for muscle recovery.', benefits:['24g Protein per serving','Zero added sugar','Digestive enzyme blend','Chocolate & Vanilla flavors','30 servings per pack'], tags:['Whey Protein','Muscle Gain','Post-Workout'] },
  { id:2, name:'PlantPower Vegan Protein', category:'Protein Powders', catKey:'protein', emoji:'🌱', badge:'New', price:1099, mrp:1299, rating:4.8, reviews:64, desc:'100% plant-based pea & brown rice blend. 20g protein. Vegan & lactose-free.', benefits:['20g Plant Protein','Pea + Brown Rice Blend','Vegan & Lactose-Free','No Artificial Colours','Unflavored & Vanilla'], tags:['Plant Protein','Vegan','Lactose-Free'] },
  { id:3, name:'Daily Vitality Multivitamin', category:'Vitamins & Supplements', catKey:'vitamins', emoji:'☀️', badge:'Popular', price:699, mrp:899, rating:4.9, reviews:203, desc:'Complete daily multivitamin with Vitamin D3, B12, Zinc & Iron. 60 capsules per pack.', benefits:['Vitamin D3 + K2','Vitamin B12 & B-Complex','Zinc & Selenium','Iron for energy','60-day supply'], tags:['Multivitamin','Daily Health','Immunity'] },
  { id:4, name:'OmegaVeda Fish Oil', category:'Vitamins & Supplements', catKey:'vitamins', emoji:'🐟', badge:'Trending', price:549, mrp:699, rating:4.7, reviews:87, desc:'High-strength Omega-3 EPA & DHA. Supports heart, brain & joint health. Lemon flavored.', benefits:['1000mg Omega-3 per capsule','EPA + DHA blend','Heart & Brain support','No fishy aftertaste','90 softgels'], tags:['Omega-3','Heart Health','Brain Health'] },
  { id:5, name:'AshwaBalance Herbal Blend', category:'Herbal Blends', catKey:'herbal', emoji:'🌿', badge:'Ayurvedic', price:549, mrp:699, rating:4.8, reviews:95, desc:'Ashwagandha + Brahmi + Shatavari. Stress relief, hormonal balance & mental clarity.', benefits:['KSM-66 Ashwagandha','Brahmi for focus','Shatavari for balance','Adaptogenic formula','60 veg capsules'], tags:['Stress Relief','Adaptogen','Hormonal Balance'] },
  { id:6, name:'TurmerCure Gold Blend', category:'Herbal Blends', catKey:'herbal', emoji:'🔥', badge:'Anti-Inflammatory', price:449, mrp:599, rating:4.9, reviews:144, desc:'Turmeric + Black Pepper + Ginger. Powerful anti-inflammatory & immunity booster.', benefits:['95% Curcumin extract','BioPerine for absorption','Ginger root extract','Anti-inflammatory','Immunity support'], tags:['Turmeric','Anti-Inflammatory','Immunity'] },
  { id:7, name:'GrowStrong Kids NutriMix', category:'Kids Nutrition', catKey:'kids', emoji:'💛', badge:'Kids Fav', price:649, mrp:799, rating:5, reviews:176, desc:'For children 2–12 years. DHA, Calcium, Iron & essential vitamins for growth and energy.', benefits:['DHA for brain development','Calcium + Vitamin D','Iron for energy','Prebiotic fibre','Chocolate & Mango flavor'], tags:['Kids 2-12','Brain Development','Growth'] },
  { id:8, name:'JuniorImmune Chewables', category:'Kids Nutrition', catKey:'kids', emoji:'🍊', badge:'Doctor Approved', price:449, mrp:599, rating:4.8, reviews:112, desc:'Chewable tablets with Vitamin C, Zinc, Elderberry & Echinacea for kids\' immunity.', benefits:['Vitamin C 250mg','Zinc for immunity','Elderberry extract','Echinacea blend','30 chewable tablets'], tags:['Kids Immunity','Chewable','Vitamin C'] },
  { id:9, name:'Casein NightRecovery', category:'Protein Powders', catKey:'protein', emoji:'🌙', badge:'Night Protein', price:1399, mrp:1699, rating:4.7, reviews:58, desc:'Micellar casein for slow-release overnight muscle recovery. 25g protein per serving.', benefits:['25g Micellar Casein','Slow-release 7–8 hrs','Overnight recovery','Rich Chocolate flavour','30 servings'], tags:['Casein','Night Protein','Recovery'] },
  { id:10, name:'VitaminD3 + K2 Drops', category:'Vitamins & Supplements', catKey:'vitamins', emoji:'🌞', badge:'Essential', price:349, mrp:499, rating:4.9, reviews:201, desc:'Liquid D3 + K2 drops. 2000IU Vitamin D3 with Vitamin K2 MK-7 for calcium absorption.', benefits:['2000IU Vitamin D3','Vitamin K2 MK-7','Liquid for fast absorption','Unflavored drops','60-day supply'], tags:['Vitamin D3','Bone Health','Immunity'] },
  { id:11, name:'TriphalaDetox Blend', category:'Herbal Blends', catKey:'herbal', emoji:'🍃', badge:'Detox', price:399, mrp:549, rating:4.6, reviews:79, desc:'Classic Triphala — Amla, Haritaki, Bibhitaki. Gentle detox, digestion & gut health.', benefits:['Amla + Haritaki + Bibhitaki','Gut health support','Gentle daily detox','Antioxidant rich','90 veg capsules'], tags:['Triphala','Gut Health','Detox'] },
  { id:12, name:'GrowTall Kids Calcium+', category:'Kids Nutrition', catKey:'kids', emoji:'🦴', badge:'Height & Bone', price:549, mrp:699, rating:4.7, reviews:93, desc:'Calcium + Vitamin D3 + Magnesium formula for growing kids. Supports height & bone density.', benefits:['500mg Calcium per serving','Vitamin D3 for absorption','Magnesium for bone strength','Ages 5–15','Vanilla flavour'], tags:['Calcium','Bone Health','Growth'] }
];
